package com.cs.exception;

import java.time.LocalDateTime;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import com.cs.bean.CartErrorResponse;
/**
 * This class is used to handle exceptions generated by CartErrorReponse class(com.cs.bean.CartErrorResponse) and
 * CartException(com.cs.exception.CartException)
 * @author Mayank Kumar(Employee ID: 46191925)
 *
 */
@ControllerAdvice
public class CartExceptionHandler
{
	@ExceptionHandler
	public ResponseEntity<CartErrorResponse> handleException(CartException exception) 
	{
		CartErrorResponse error = new CartErrorResponse();
		error.setMessage(exception.getMessage());
		error.setTimeStamp(LocalDateTime.now());
		return new ResponseEntity<>(error, HttpStatus.NOT_FOUND);
	}
}
