package com.cs.exception;

import java.time.LocalDateTime;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;

import com.cs.bean.GardenDecorErrorResponse;
/**
 * This class is used to handle exceptions generated by GardenDecorErrorReponse class(com.cs.bean.GardenDecorErrorResponse) and
 * GardenDecorException(com.cs.exception.GardenDecorException)
 * @author Mayank Kumar(Employee ID: 46191925)
 *
 */
@ControllerAdvice
public class GardenDecorExceptionHandler 
{
	@ExceptionHandler
	public ResponseEntity<GardenDecorErrorResponse> handleException(GardenDecorException exception) 
	{
		GardenDecorErrorResponse error = new GardenDecorErrorResponse();
		error.setMessage(exception.getMessage());
		error.setTimeStamp(LocalDateTime.now());
		return new ResponseEntity<>(error, HttpStatus.NOT_FOUND);
	}
}
